### ISSUE TITLE
Sharing read-only data among students

### ISSUE THREAD

**Issue by Chiil** [2i2c-org/pilot#19]
I noticed two folders in my accounts with the names `shared` and `shared-readwrite`. I would really like to share a dataset of approximately 50 MB among the students, that they will all open at the same time (30 students). Is this possible, or is it better to put the file separately in each account?

**Comment by choldgraf** [comment]
Yep - that's a great use-case for the `shared-readwrite` folder 👍

**Comment by Chiil** [comment]
But what is the difference between `shared` and `shared-readwrite`? Which one is read-only? I do not want them to be abel to edit the file.

**Comment by choldgraf** [comment]
`shared-readwrite/` is *only* available to administrators, and anything that is put into that folder will show up in `shared/` for *all* hub users. So in order to make something show up in `shared/`, an administrator should put it into `shared-readwrite/`.

**Comment by Chiil** [comment]
Alright, clear!
