### ISSUE TITLE
Unable to push to GitHub from 2i2c JupyterHub using ssh-key authentication

### ISSUE THREAD

**Issue by zaneselvans** [2i2c-org/pilot#30]
In order to facilitate collaboration on our hub, it would be useful if we could edit notebooks there, push them to GitHub, and have other collaborators pull them down to their own user space on the hub, make changes, and push them back to GitHub, etc. This way we would know we are sharing a common data + computational environment, and not have to worry about debugging issues that are tied to our local configuration / environment.

Cloning public GitHub repos to the hub works fine, but I had trouble pushing changes back to GitHub. I have 2-factor authentication set up on my GitHub account, and so https:// + username and password doesn't work. I've been authenticating with my SSH key, but that doesn't seem to be working here.

* **Hub URL:** https://catalyst-cooperative.pilot.2i2c.cloud
* **What you expected to happen:** I thought I would be able to add an SSH key and use it to authenticate with GitHub, allowing me to push changes.
* **What actually happened:** I was unable to add my SSH key on the JupyterHub.
* **Any error messages you see:** 
```sh
jovyan@jupyter-zane-2eselvans-40catalyst-2ecoop:~/.ssh$ ssh-add id_rsa
Could not open a connection to your authentication agent.
```

I was ultimately able to get https based authentication working by [generating a personal access token](https://webkul.com/blog/github-push-with-two-factor-authentication/), and telling git to store the credential locally for later re-use, but I'm still curious if I was just doing something wrong with respect to getting SSH authentication working, and whether ssh-key based authentication would be an easy thing to enable, so the access token isn't being stored as cleartext on the hub.

Also wondering if there is a preferred solution for running git commands within JupyterLab, for collaborators with less terminal / CLI familiarity.

**Comment by zaneselvans** [comment]
I was eventually able to add my ssh-key by running:
```
eval `ssh-agent -s`
```
to set the required environment variables, but the push still failed:
```
jovyan@jupyter-zane-2eselvans-40catalyst-2ecoop:~/code/pudl$ git push
ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists.
```
So I imagine port 22 is just closed by default on the hub or something.

**Comment by yuvipanda** [comment]
w00t, thanks for digging into this, @zaneselvans. You're indeed correct that we block outgoing ssh by default. I've enabled it now, try again?
