### ISSUE TITLE
Increase RAM to 4GB on Catalyst Cooperative pilot hub?

### ISSUE THREAD

**Issue by zaneselvans** [2i2c-org/pilot#31]
### What would you like to see changed on the hub:
It looks like many of the things we typically do in Jupyter take at least 2.5 GB of RAM (based on running processes locally with the `nbresuse` plugin activated), and the kernel is predictably dying when we try to run those things on [our pilot hub](https://catalyst-cooperative.pilot.2i2c.cloud/)

### Any particular steps you think are needed to accomplish this:
Would it be possible to bump the RAM to 4GB?

### How quickly do you need this change to be made:
We can play around with configurations on the hub as it is, but to start sharing it with a couple of collaborators and exploring how we can use the JupyterHub to improve our workflow, we'll need more memory so... some time this coming week would be great.

### How can we be good stewards of the server resources?
Obviously increasing the per-node resources increases overall costs. What can we do to ensure we aren't needlessly consuming resources? How long does the server keep running and holding on to resources after we go idle? Can we minimize impacts on the overall cost by shutting the server down as soon as we're done using it for a while?

**Comment by yuvipanda** [comment]
Hey @zaneselvans! https://github.com/2i2c-org/pilot-hubs/pull/101 has been merged, which should increase your limit & guarantee. Can you try out?

**Comment by zaneselvans** [comment]
Hey @yuvipanda I restarted my server and tried to run the same operation, and it failed again after getting to 2GB of memory usage, and the `nbresuse` display in the lower left hand corner of the notebook still says the limit is 2048 MB. Does the whole hub need to be restarted? If I "Shutdown Hub" will it bring itself back up again?

**Comment by choldgraf** [comment]
Your user server should need to be restarted. When you say “shutdown server” do you mean you had to re-log in again, or did you just restart the notebook server?

**Comment by zaneselvans** [comment]
Ah no I just shut down my notebook server I think. I did not have to log in again.

**Comment by zaneselvans** [comment]
Hmm. Still not getting a change in the memory allocation. Things I have done:
* Restarted the notebook kernel.
* Logged out of the hub and logged back in.
* Clicked the red "stop server" button next to my email on the [hub admin page](https://catalyst-cooperative.pilot.2i2c.cloud/hub/admin)
* Clicked the red "Stop My Server" button on the [hub home page](https://catalyst-cooperative.pilot.2i2c.cloud/hub/home) and then restarted it with the blue "Start My Server" button.

Things I have not done:
* Shut down the hub with the big red "Shutdown Hub" button in the upper right hand portion of the [hub admin page](https://catalyst-cooperative.pilot.2i2c.cloud/hub/admin).

**Comment by choldgraf** [comment]
I just logged in and found the same thing that you did @zaneselvans:

![image](https://user-images.githubusercontent.com/1839645/100134795-9e616d80-2e3d-11eb-855e-8f5e6396570e.png)

Will try and figure out what's up

**Comment by choldgraf** [comment]
ah I figured it out @zaneselvans - was a mistake in the config that I had made. Try turning your user session off and on again and you should now have 4GB guaranteed, 6GB max per user 👍

**Comment by zaneselvans** [comment]
Yep, it's working now!
