### ISSUE TITLE
server start up failures (spawn failed)

### ISSUE THREAD

**Issue by guebelsn** [2i2c-org/pilot#45]
Thanks for reporting your issue! Sorry things aren't working as expected.

In order to help resolve things quickly, please provide the following information:

✔️ The URL of your hub:
https://sbcc.cloudbank.2i2c.cloud/
✔️ What you expected to happen:
✔️ What actually happened:
I was able to log in and launch the server, but when I tried to use it (just starting a notebook), it stopped working, tried to relaunch, but that also failed
✔️ Any error messages you see:
Spawn failed
The latest attempt to start your server has failed. 
Tried relaunching and logging out, but that did not seem to help.
✔️ Any specific packages or tools you were using:
I am just trying to get started, but it seems very unstable... This happened 2 weeks ago as well.

**Comment by choldgraf** [comment]
Hmm - just to confirm, is this *always* happening, or just sometimes? (I just tried starting up a server on this hub and it worked OK, so I wonder if there is some kind of resource constraint that is being used up elsewhere)

**Comment by guebelsn** [comment]
Looks like it just started working again. Please let me know if it would help if I monitored something and/or if anyone knows why this is happening. I am currently just trying to get familiar with the platform as I am planning on using it to teach a course in Fall 2021 (starting in August).

**Comment by choldgraf** [comment]
well in general you definitely shouldn't need to monitor anything 😅 that'd be a bug on our side, not on yours :-)

It could be that some minor bugs will pop here and there as people start using the infrastructure more, so these issues are really helpful at spotting where there are wrinkles to smooth over

**Comment by guebelsn** [comment]
Thank you for getting back to me so quickly! Excited to be part of the pilot program. I haven't had much time to use it yet, but hope to do a little more before August. I will let you know if it happens again.

**Comment by choldgraf** [comment]
awesome, thanks very much for bearing with us :-) don't hesitate to flag stuff if you think the infrastructure is being buggy!

**Comment by yuvipanda** [comment]
Sorry you ran into this, @guebelsn! I dug in a bit, and have a clear cause here: https://github.com/2i2c-org/pilot-hubs/issues/222. I think it should be ok for the rest of the day, and we'll try get the root cause fixed soon. Thank you for your patience!

**Comment by guebelsn** [comment]
Thank you!

**Comment by yuvipanda** [comment]
This has since been fixed.
