### ISSUE TITLE
Clarify that user-installed packages have unpredictable results

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/pilot#58]
# Background

In https://github.com/2i2c-org/pilot/issues/57 a user was unable to access their server because they had (unintentionally/intentionally) installed a package via `--user`. This had upgraded `nbconvert` and introduced a bug that meant servers couldn't start.

It may be common for users to use `--user` to install things (unless we explicitly allow it). We should provide lots of documentation for administrators that suggests to them this is a potential cause of inexplicable problems.

# To Do

- [x] Find places in the docs where we should include a warning about `--user`.
- [ ] Consider adding this check to the `bug` issue template
- [x] Make a PR to make these changes

**Comment by yuvipanda** [comment]
https://2i2c.org/pilot/admin/howto/environment.html#temporarily-install-packages-for-a-session is present now.

**Comment by choldgraf** [comment]
I think this is done
