### ISSUE TITLE
Adding non-admin users with different domain names

### ISSUE THREAD

**Issue by JILPulvino** [2i2c-org/pilot#59]
We would like to add users with non @justiceinnovationlab.org domains and ideally change the log in to github authentication. to make it easier to add future non-admin users.

**Comment by yuvipanda** [comment]
We can definitely just change it to GitHub. Can you give us the admin's github usernames? If you want to retain the data in current home directories, you can also give us a mapping of current email address -> github username so we can do a migration.

**Comment by JILPulvino** [comment]
Yep, thank you!

donald.braman@justiceinnovationlab.org -> donaldbraman
rory.pulvino@justiceinnovationlab.org -> JILPulvino

**Comment by JILPulvino** [comment]
Would you also be able to add a regular user (github username cortiz27) with the switch to github?

**Comment by choldgraf** [comment]
@JILPulvino yep as an administrator you can define whatever username you'd like, as long as it matches the authentication provider you're using. So now that your hub uses GitHub, you can add *other github handles* via the admin panel, and they'll be added to the hub as users.

**Comment by JILPulvino** [comment]
This is great, thank you. Clarification - I've added the user I wanted to (cortiz27), but after pulling the master branch, I don't actually see an update to the YAML file reflecting this. Is this because regular users are not defined in the YAML file?

**Comment by yuvipanda** [comment]
> Is this because regular users are not defined in the YAML file?

Yep, that is correct! Only admin users are in the YAML file, everyone else is in a database.

**Comment by JILPulvino** [comment]
Great, thank you
