### ISSUE TITLE
Properly isolating project repos among users

### ISSUE THREAD

**Issue by JILPulvino** [2i2c-org/pilot#61]
Among the people using the hub, some of the users should have access to one repo while another user should have access to a different repo. What's the best way for me to guarantee that if users clone repos that those repos don't end up shared with users that shouldn't have access to them? Is it as simple as they clone the repo NOT in the shared folder?

**Comment by yuvipanda** [comment]
Hi @JILPulvino :)

You are right - as long as you don't put anything in the 'shared' folder, users will only have access to what's cloned in their home directory. We're adding some more docs about shared directory [here](https://github.com/2i2c-org/pilot/pull/55/files#diff-58096adff46339199ce930346f412856617e04e9b1cb1d81bfccc876c6095fa0), hopefully that'll be merged soon.

**Comment by JILPulvino** [comment]
Great, thank you!
