### ISSUE TITLE
Give admins/teachers more memory

### ISSUE THREAD

**Issue by solomonlr** [2i2c-org/pilot#64]
Thanks for requesting an improvement to your hub. 👍

In order to help resolve your request, please provide the following information:

https://elcamino.cloudbank.2i2c.cloud/user/srussell@elcamino.edu

✔️ What would you like to see changed on the hub: Please give admins/teachers more memory on the hub
✔️ Any particular steps you think are needed to accomplish this: N/A
✔️ How quickly do you need this change to be made: ASAP, I'm teaching at 2:30 pm today and my kernel is crashing on large data sets from the Data8 course
✔️ Are there any alternative ways to accomplish what you're trying to do: Without this, the lecture will not be interactive.

We'll take this into consideration and try to get back to you quickly!

**Comment by yuvipanda** [comment]
I am just  giving everyone 2G of RAM. Can you tell me when your class ends so we can figure out more details afterwards?

**Comment by yuvipanda** [comment]
Ok, everyone should have 2G of RAM now.

**Comment by solomonlr** [comment]
Thanks, today's class ends at 5:25. The semester ends June 11th.

**Comment by choldgraf** [comment]
I believe that this is resolved, so closing this, but if it isn't please feel free to reopen!
