### ISSUE TITLE
Update otter-grader

### ISSUE THREAD

**Issue by shawnwiggins** [2i2c-org/pilot#71]
Thanks for requesting an improvement to your hub. 👍

In order to help resolve your request, please provide the following information:

- What would you like to see changed on the hub: **Please, update otter-grader to the current version. Thank you!**
- Any particular steps you think are needed to accomplish this:
- How quickly do you need this change to be made: **As soon as possible. We can upgrade individually for the time being to practice using the Otter documentation tutorials.**
- Are there any alternative ways to accomplish what you're trying to do:

We'll take this into consideration and try to get back to you quickly!

**Comment by yuvipanda** [comment]
Thanks for opening this here, @shawnwiggins. Should work once https://github.com/2i2c-org/pilot-hubs/pull/416 is merged

**Comment by yuvipanda** [comment]
@shawnwiggins should be updated now.
