### ISSUE TITLE
Remove references about ephemeral-hub from the docs

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/pilot#74]
A link to ephemeral-hubs is broken, is this still a supported type of hub?

https://pilot.2i2c.org/en/latest/about/infrastructure.html#ephemeral-hubs

**Comment by GeorgianaElena** [comment]
It's been removed in https://github.com/2i2c-org/pilot-hubs/pull/361. We should remove it from the docs too.
Ty for finding this @consideRatio <3

**Comment by choldgraf** [comment]
this is fixed!
