### ISSUE TITLE
Fix link to hub-specific config file to match the new structure

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/pilot#75]
On this page: https://pilot.2i2c.org/en/latest/admin/howto/replicate.html

In this section:

![image](https://user-images.githubusercontent.com/3837114/119897916-63054000-bf41-11eb-91c7-1f32dc2c1f41.png)

A link to https://github.com/2i2c-org/pilot-hubs/blob/master/hubs.yaml is broken.

**Comment by damianavila** [comment]
Yep, the structure was changed recently (a few weeks ago), this is the folder we should be linking instead: https://github.com/2i2c-org/pilot-hubs/tree/master/config/hubs

**Comment by choldgraf** [comment]
I believe this is fixed!
