### ISSUE TITLE
request install R package 'lwgeom'

### ISSUE THREAD

**Issue by caitlinkroeger** [2i2c-org/pilot#79]
I am using the farallon 2i2c cloud to run RStudio and would like the 'lwgeom' package to be installed. Thank you!

**Comment by yuvipanda** [comment]
@caitlinkroeger can you try it now?

**Comment by caitlinkroeger** [comment]
@yuvipanda no luck yet

**Comment by yuvipanda** [comment]
I think I finally got it right, but I had to upgrade R to 4.0.5 and RStudio to 1.3 alongside. A bunch of other package versions also needed to change, but now `library(lwgeom)` works for me! Can you test it out?

**Comment by choldgraf** [comment]
closing this one as I think it's resolved, but please re-open if this doesn't work!
