### ISSUE TITLE
Upgrade Otter

### ISSUE THREAD

**Issue by shawnwiggins** [2i2c-org/pilot#86]
Can you up please update otter-grade from 2.1.7 to its current version (2.2.5) on the hub https://ccsf.cloudbank.2i2c.cloud/

We would appreciate this change as quickly as possible. 

Thank you!

**Comment by yuvipanda** [comment]
Thanks for opening the issue, @shawnwiggins. @sean-morris is going to take this up

**Comment by yuvipanda** [comment]
Should be fixed now - thanks @sean-morris!

**Comment by shawnwiggins** [comment]
Thanks!
